import { Inter, Playfair_Display } from "next/font/google";  // Import her
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import WhatsAppFloatingButton from "@/components/WhatsAppFloatingButton";


// Define the fonts with CSS variables (matching your existing --font-heading and --font-body)
const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-body",          // Matches your existing variable
  display: "swap",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${inter.variable}  antialiased`}
      >
        <ThemeProvider
          attribute="class"      // Adds 'dark' class to <html>
          defaultTheme="system"  // Optional: start with system preference
          enableSystem           // Optional: respect OS setting
        >
          <Header />
          {children}
          <WhatsAppFloatingButton />  
          <Footer />
          
        </ThemeProvider>
      </body>
    </html>
  );
}
